articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.article_list, name='article_list'),
    path('create/', views.create_article, name='create_article'),
    path('<int:article_pk>/', views.article_detail, name='article_detail'),
    path('<int:article_pk>/update/', views.update_article, name='update_article'),
    path('<int:article_pk>/delete/', views.delete_article, name='delete_article'),
    path('<int:article_pk>/comment/create/', views.create_comment, name='create_comment'),
    path('<int:article_pk>/<int:comment_pk>/comment/update/', views.update_comment, name='update_comment'),
    path('<int:article_pk>/<int:comment_pk>/comment/delete/', views.delete_comment, name='delete_comment'),
    path('<int:article_pk>/like/', views.like_article, name='like_article'),
]

hemstagram/urls.py
from django.contrib import admin
from django.urls import path, include
from articles import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('photos/', include('photos.urls')),
    path('', views.article_list),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photos/urls.py
from django.urls import path
from . import views

app_name = 'photos'

urlpatterns = [
    path('', views.photo_list, name='photo_list'),
    path('create/', views.create_photo, name='create_photo'),
    path('<int:photo_pk>/', views.photo_detail, name='photo_detail'),
    path('<int:photo_pk>/update/', views.update_photo, name='update_photo'),
    path('<int:photo_pk>/delete/', views.delete_photo, name='delete_photo'),
    path('<int:photo_pk>/comments/', views.create_comment, name='create_comment'),
    path('<int:photo_pk>/comments/<int:comment_pk>/update/', views.update_comment, name='update_comment'),
    path('<int:photo_pk>/comments/<int:comment_pk>/delete/', views.delete_comment, name='delete_comment'),
    path('<int:photo_pk>/like/', views.like_photo, name='like_photo'),
    path('<int:photo_pk>/comments/<int:comment_pk>/like/', views.like_comment, name='like_comment'),
]

articles/models.py
from django.db import models
from django.conf import settings

class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='my_articles')
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='my_comments')
    opinion = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

articles/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ('title', 'content',)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('opinion', )
        widgets = {
            'opinion': forms.TextInput(
                attrs={
                    'placeholder': '댓글 달기',
                }
            )
        }

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST, require_GET, require_http_methods
from django.core.paginator import Paginator
from django.http import JsonResponse
from .forms import ArticleForm, CommentForm
from .models import Article, Comment

@require_GET
@login_required
def article_list(request):
    articles = Article.objects.order_by('-created_at')
    paginator = Paginator(articles, 10)
    page = request.GET.get('page')
    page_obj = paginator.get_page(page)
    context = {
        'articles': articles,
        'page_obj': page_obj
    }
    return render(request, 'articles/article_list.html', context)

@login_required
@require_http_methods(['GET', 'POST'])
def create_article(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.author = request.user
            article.save()
            return redirect('articles:article_detail', article.pk)
    else:
        form = ArticleForm()
    context = {
        'form': form
    }
    return render(request, 'articles/form.html', context)

@require_GET
@login_required
def article_detail(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    form = CommentForm()
    context = {
        'article': article,
        'form': form
    }
    return render(request, 'articles/article_detail.html', context)

@login_required
@require_http_methods(['GET', 'POST'])
def update_article(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    if request.method == 'POST':
        form = ArticleForm(request.POST, instance=article)
        if form.is_valid():
            form.save()
            return redirect('articles:article_detail', article.pk)
    else:
        form = ArticleForm(instance=article)
    context = {
        'form': form
    }
    return render(request, 'articles/form.html', context)

@require_POST
@login_required
def delete_article(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    article.delete()
    return redirect('articles:article_list')

@require_POST
@login_required
def create_comment(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.article = article
        comment.save()
    return redirect('articles:article_detail', article.pk)

@login_required
@require_http_methods(['GET', 'POST'])
def update_comment(request, article_pk, comment_pk):
    article = get_object_or_404(Article, pk=article_pk)
    comment = get_object_or_404(Comment, pk=comment_pk)
    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.article = article
            comment.save()
            return redirect('articles:article_detail', article.pk)
    else:
        form = CommentForm(instance=comment)
    context = {
        'form': form,
        'article': article,
    }
    return render(request, 'articles/update_comment.html', context)

@require_POST
@login_required
def delete_comment(request, article_pk, comment_pk):
    article = get_object_or_404(Article, pk=article_pk)
    comment = get_object_or_404(Comment, pk=comment_pk)
    if request.user == comment.author:
        comment.delete()
    return redirect('articles:article_detail', article.pk)

@login_required
def like_article(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    user = request.user
    # 만약 내가 이 글을 좋아요를 누른 상태라면
    if user in article.like_users.all():
        article.like_users.remove(user)
        is_liked = False
    # 내가 이 글을 좋아요를 누른 상태가 아니라면
    else:
        article.like_users.add(user)
        is_liked = True
    result = article.like_users.all()
    result = list(result.values('username'))
    data = {
        'is_liked': is_liked,
        'result': result,
        'user': str(user),
    }
    return JsonResponse(data)

articles/templates/articles/article_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block static %}
<link rel="stylesheet" href="{% static 'css/article_form.css' %}">
<link rel="stylesheet" href="{% static 'css/article_detail.css' %}">
<script src="{% static 'js/article_like.js' %}"></script>
{% endblock %}

{% block body %}
    <h1>{{ article.title }}</h1>
    <p>{{ article.author }} | {{ article.created_at }}</p>
    <hr>
    <p>{{ article.content }}</p>
    <hr>
    {% if request.user == article.author %}
        <form action="{% url 'articles:delete_article' article.pk %}" method="POST">
            {% csrf_token %}
            <div class="d-flex justify-content-end mb-4">
                <a class="btn btn-grad text-white mx-2" href="{% url 'articles:update_article' article.pk %}" role="button">수정</a>
            <button class="btn btn-light">삭제</button>
            </div>
        </form>
    {% endif %}
    <div class="mb-2">
        {% if request.user in article.like_users.all %}
            <i data-article_pk="{{ article.pk }}" id="likeArticleButton" class="fas fa-heart mr-2 like-btn">좋아요 해제</i>
        {% else %}
            <i data-article_pk="{{ article.pk }}" id="likeArticleButton" class="fas fa-heart mr-2 like-btn">좋아요</i>
        {% endif %}
    </div>
    <div class="mb-4">
        <span>
            {% if article.like_users.count == 0 %}
                <span id="likeUsers{{ article.pk }}"></span>
            {% else %}
                {% for user in article.like_users.all %}
                    <span id="likeUsers{{ article.pk }}">{{ user.username }}</span>
                {% endfor %}
            {% endif %}
            님이 좋아합니다.
        </span>
    </div>
    <i class="far fa-comment comment-img"></i>
    <strong class="comment-count-info">댓글 {{ article.comments.count }}개</strong>
    {% for comment in article.comments.all|dictsortreversed:"created_at" %}
        <div class="d-flex justify-content-between mt-3">
            <div>
                <div class="mb-1">
                    <strong>{{ comment.author }}</strong>
                    <span class="text-option">{{ comment.created_at }}</span>
                </div>
                <p>{{ comment.opinion }}</p>
            </div>
            {% if request.user == comment.author %}
                <div class="dropdown mr-1">
                    <button type="button" class="btn btn-light dropdown-toggle comment-dropdown-img" id="dropdownMenuOffset" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-offset="10,20">
                      ...
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuOffset">
                      <a class="dropdown-item" href="{% url 'articles:update_comment' article.pk comment.pk %}">수정</a>
                      <a class="dropdown-item" href="{% url 'articles:delete_comment' article.pk comment.pk %}">삭제</a>
                    </div>
                </div>
            {% endif %}
        </div>
    {% endfor %}
    <div class="mt-4">
        <form action="{% url 'articles:create_comment' article.pk %}" method="POST">
            {% csrf_token %}
            {% bootstrap_form form layout='inline' %}
            <div class="d-flex justify-content-end">
                <button class="btn btn-grad text-white">댓글</button>
                <a class="btn btn-light mx-2 btn-cancel" href="{% url 'articles:article_detail' article.pk %}" role="button">취소</a>
            </div>
        </form>
    </div>
{% endblock %}

articles/templates/articles/article_list.html
{% extends 'base.html' %}
{% load bootstrap_pagination %}

{% block body %}
    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">제목</th>
          <th scope="col">작성자</th>
          <th scope="col">작성일</th>
        </tr>
      </thead>
      <tbody>
        {% for article in page_obj %}
          <tr>
            <th scope="row">{{ article.pk }}</th>
            <td><a class="text-decoration-none text-dark" href="{% url 'articles:article_detail' article.pk %}">{{ article.title }}[{{ article.comments.count }}]</a></td>
            <td>{{ article.author }}</td>
            <td>{{ article.created_at }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    {% bootstrap_paginate page_obj range=5 show_prev_next="true" previous_label="prev" show_first_last="true" next_label="next" extra_pagination_classes="justify-content-center mt-5" %}
{% endblock %}

articles/templates/articles/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block static %}
<link rel="stylesheet" href="{% static 'css/article_form.css' %}">
{% endblock %}
{% block body %}
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <div class="float-right">
            {% if request.path == "/articles/create/" %}
                <button class="btn btn-grad text-white">제출</button>
            {% else %}
                <button class="btn btn-grad text-white">수정</button>
            {% endif %}
            <a class="btn btn-light" href="{% url 'articles:article_list' %}" role="button">취소</a>
        </div>
    </form>
{% endblock %}

articles/templates/articles/update_comment.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block static %}
<link rel="stylesheet" href="{% static 'css/article_form.css' %}">
{% endblock %} 

{% block body %}
    <h1>{{ article.title }}</h1>
    <p>{{ article.author }} | {{ article.created_at }}</p>
    <hr>
    <p>{{ article.content }}</p>
    <hr>
    <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form layout='inline' %}
        <div class="d-flex justify-content-end">
            <button class="btn btn-grad text-white">수정</button>
            <a class="btn btn-light mx-2" href="{% url 'articles:article_detail' article.pk %}" role="button">취소</a>
        </div>
    </form>
{% endblock %}