hemstagram/urls.py
from django.contrib import admin
from django.urls import path, include
from articles import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('photos/', include('photos.urls')),
    path('', views.article_list),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photos/urls.py
from django.urls import path
from . import views

app_name = 'photos'

urlpatterns = [
    path('', views.photo_list, name='photo_list'),
    path('create/', views.create_photo, name='create_photo'),
    path('<int:photo_pk>/', views.photo_detail, name='photo_detail'),
    path('<int:photo_pk>/update/', views.update_photo, name='update_photo'),
    path('<int:photo_pk>/delete/', views.delete_photo, name='delete_photo'),
    path('<int:photo_pk>/comments/', views.create_comment, name='create_comment'),
    path('<int:photo_pk>/comments/<int:comment_pk>/update/', views.update_comment, name='update_comment'),
    path('<int:photo_pk>/comments/<int:comment_pk>/delete/', views.delete_comment, name='delete_comment'),
    path('<int:photo_pk>/like/', views.like_photo, name='like_photo'),
    path('<int:photo_pk>/comments/<int:comment_pk>/like/', views.like_comment, name='like_comment'),
]

photos/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill, Thumbnail

class Photo(models.Model):
    content = models.TextField()
    image = models.ImageField()
    image_thumbnail = ImageSpecField(source='image',
                         processors=[ResizeToFill(250, 250)],
                         format='JPEG',
                         options={'quality': 100})
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='my_photos')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_photos')

class Comment(models.Model):
    photo = models.ForeignKey(Photo, on_delete=models.CASCADE, related_name='photo_comments')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='photo_my_comment')
    opinion = models.CharField(max_length=300)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_comments')

photos/forms.py
from django import forms
from .models import Photo, Comment

class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ('image', 'content')
        widgets = {
            'content': forms.Textarea(
                attrs={
                    'placeholder': '나의 이야기',
                    }
            ),
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('opinion', )
        widgets = {
            'opinion': forms.TextInput(
                attrs={'placeholder': '댓글 달기',
                       'class': 'comment-input',
            }),
        }

photos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_GET, require_POST, require_http_methods
from django.http import JsonResponse
from .models import Photo, Comment
from .forms import PhotoForm, CommentForm

@require_GET
@login_required
def photo_list(request):
    photos = Photo.objects.order_by('-created_at')
    form = CommentForm()
    context = {
        'photos': photos,
        'form': form
    }
    return render(request, 'photos/photo_list.html', context)

@login_required
@require_http_methods(['GET', 'POST'])
def create_photo(request):
    if request.method == 'POST':
        form = PhotoForm(request.POST, request.FILES)
        if form.is_valid():
            photo = form.save(commit=False)
            photo.author = request.user
            photo.save()
            return redirect('photos:photo_list')
    else:
        form = PhotoForm()
    context = {
        'form': form
    }
    return render(request, 'photos/form.html', context)

@require_GET
@login_required
def photo_detail(request, photo_pk):
    photo = get_object_or_404(Photo, pk=photo_pk)
    form = CommentForm()
    context = {
        'photo': photo,
        'form': form
    }
    return render(request, 'photos/photo_detail.html', context)

@login_required
@require_http_methods(['GET', 'POST'])
def update_photo(request, photo_pk):
    photo = get_object_or_404(Photo, pk=photo_pk)
    if request.method == 'POST':
        form = PhotoForm(request.POST, request.FILES, instance=photo)
        if form.is_valid():
            form.save()
            return redirect('photos:photo_detail', photo.pk)
    else:
        form = PhotoForm(instance=photo)
    context = {
        'form': form
    }
    return render(request, 'photos/form.html', context)

@require_POST
@login_required
def delete_photo(request, photo_pk):
    photo = get_object_or_404(Photo, pk=photo_pk)
    if request.user == photo.author:
        photo.delete()
    else:
        messages.error(request, '권한이 없습니다.')
    return redirect('photos:photo_list')

@require_POST
@login_required
def create_comment(request, photo_pk):
    photo = get_object_or_404(Photo, pk=photo_pk)
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.photo = photo
        comment.save()
    return redirect('photos:photo_detail', photo.pk)

@login_required
@require_POST
def update_comment(request, photo_pk, comment_pk):
    photo = get_object_or_404(Photo, pk=photo_pk)
    comment = get_object_or_404(Comment, pk=comment_pk)
    form = CommentForm(request.POST, instance=comment)
    if form.is_valid():
        comment.save()
    return redirect('photos:photo_detail', photo.pk)

@require_POST
@login_required
def delete_comment(request, photo_pk, comment_pk):
    photo = get_object_or_404(Photo, pk=photo_pk)
    comment = get_object_or_404(Comment, pk=comment_pk)
    if request.user == comment.author:
        comment.delete()
    return redirect('photos:photo_detail', photo.pk)

@login_required
def like_photo(request, photo_pk):
    photo = get_object_or_404(Photo, pk=photo_pk)
    user = request.user
    if user in photo.like_users.all():
        photo.like_users.remove(user)
        is_liked = False
    else:
        photo.like_users.add(user)
        is_liked = True
    data = {
        'is_liked': is_liked,
        'like_count': photo.like_users.count()
    }
    return JsonResponse(data)

def like_comment(request, photo_pk, comment_pk):
    photo = get_object_or_404(Photo, pk=photo_pk)
    comment = get_object_or_404(Comment, pk=comment_pk)
    user = request.user
    if user in comment.like_users.all():
        comment.like_users.remove(user)
        is_liked = False
    else:
        comment.like_users.add(user)
        is_liked = True
    data = {
        'is_liked': is_liked,
        'like_count': comment.like_users.count()
    }
    return JsonResponse(data)

photos/templates/photos/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block static %}
<link rel="stylesheet" href="{% static 'css/photo_form.css' %}">
{% endblock %}

{% block body %}
    <div class="container">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form layout='inline' %}
            <div class="float-right">
                {% if request.path == "/photos/create/" %}
                    <button class="btn btn-grad text-white">업로드</button>
                {% else %}
                    <button class="btn btn-grad text-white">수정</button>
                {% endif %}
                <a class="btn btn-light" href="{% url 'photos:photo_list' %}" role="button">취소</a>
            </div>
        </form>
    </div>
{% endblock %}

photos/templates/photos/photo_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block static %}
<link rel="stylesheet" href="{% static 'css/photo_detail.css' %}">
<script src="{% static 'js/photo_like.js' %}"></script>
<script src="{% static 'js/photo_comment.js' %}"></script>
{% endblock %}

{% block body %}
    <div class="card mb-5">
        <div class="row no-gutters card-height">
        <div class="col-md-7 card-height">
            <img src="{{ photo.image.url }}" class="card-img" alt="..." height="100%">
        </div>
        <div class="col-md-5">
            <div class="card-body d-flex align-items-center bd-highlight py-3">
                <div class="bd-highlight">
                    <a href="#" class="text-dark"><i class="fas fa-user-circle mr-3 profile-photo"></i></a>
                </div>
                <div class="bd-highlight">
                    <strong>{{ photo.author }}</strong>
                </div>
                {% if request.user == photo.author %}
                    <div class="ml-auto p-2 bd-highlight">
                        <a data-toggle="modal" href="#myPhoto{{ photo.pk }}" class="text-dark"><i class="fas fa-ellipsis-h"></i></a>
                        <div class="modal photo-options" id="myPhoto{{ photo.pk }}" tabindex="-1" role="dialog">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-body">
                                        <a class="text-dark" href="{% url 'photos:update_photo' photo.pk %}"><p>수정</p></a>
                                        <form action="{% url 'photos:delete_photo' photo.pk %}" method="POST">
                                            {% csrf_token %}
                                            <button class="btn text-dark pl-0 btn-del"><p>삭제<p></button>
                                        </form>
                                        <a type="link" class="text-dark cursor-pointer" data-dismiss="modal">취소</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
            <hr class="my-0">
            <div class='comment-list'>
                <div class="card-body d-flex align-items-center pb-0">
                    <i class="fas fa-user-circle mr-3 profile-photo"></i>
                    <strong>{{ photo.author }} </strong>
                </div>
                <div class="container">
                    <p class="my-0 photo-title">{{ photo.content }}</p>  
                </div>
                <div class="card-body pt-0 photo-created">
                    <span class="option-text">{{ photo.created_at }}</span>
                </div>
                {% for comment in photo.photo_comments.all|dictsortreversed:"created_at" %}
                    <div class="card-body d-flex align-items-center bd-highlight pb-0">
                        <div class="bd-highlight">
                            <i class="fas fa-user-circle mr-3 profile-photo"></i>
                        </div>
                        <div class="bd-highlight">
                            <strong>{{ comment.author }} </strong>
                        </div>
                        {% if request.user == comment.author %}
                            <div class="ml-auto p-2 bd-highlight">
                                <a data-toggle="modal" class="text-dark" href="#myPhoto{{ comment.pk }}"><i class="fas fa-ellipsis-h"></i></a>
                                <div class="modal photo-options" id="myPhoto{{ comment.pk }}" tabindex="-1" role="dialog">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-body">
                                                <a data-toggle="modal" class="text-dark" href="#myComment{{ comment.pk }}"><p>수정</p></a>
                                                <div class="modal photo-options" tabindex="-1" role="dialog" id="myComment{{ comment.pk }}">
                                                    <div class="modal-dialog">
                                                      <div class="modal-content">
                                                        <div class="modal-body">
                                                            <form id="commentForm" action="{% url 'photos:update_comment' photo.pk comment.pk %}" method="POST">
                                                                {% csrf_token %}
                                                                {% bootstrap_form form layout='inline' %}
                                                                <div class="float-right">
                                                                    <button class="btn comment-button">수정</button>
                                                                    <a type="button" class="btn btn-close" data-dismiss="modal">닫기</a>
                                                                </div>
                                                            </form>
                                                        </div>
                                                      </div>
                                                    </div>
                                                </div>
                                                <form action="{% url 'photos:delete_comment' photo.pk comment.pk %}" method="POST">
                                                    {% csrf_token %}
                                                    <button class="btn text-dark pl-0 btn-del"><p>삭제<p></button>
                                                </form>
                                                <a type="link" class="text-dark cursor-pointer" data-dismiss="modal">취소</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="p-2 bd-highlight">
                                {% if request.user in comment.like_users.all %}
                                    <i data-photo_pk="{{ photo.pk }}" data-comment_pk="{{ comment.pk }}" class="commentLikeButton fas fa-heart comment-liked-heart"></i>
                                {% else %}
                                    <i data-photo_pk="{{ photo.pk }}" data-comment_pk="{{ comment.pk }}" class="commentLikeButton far fa-heart comment-unliked-heart"></i>
                                {% endif %}
                            </div>
                        {% else %}
                            <div class="py-2 px-4 ml-auto bd-highlight">
                                {% if request.user in comment.like_users.all %}
                                    <i data-photo_pk="{{ photo.pk }}" data-comment_pk="{{ comment.pk }}" class="commentLikeButton fas fa-heart comment-liked-heart"></i>
                                {% else %}
                                    <i data-photo_pk="{{ photo.pk }}" data-comment_pk="{{ comment.pk }}" class="commentLikeButton far fa-heart comment-unliked-heart"></i>
                                {% endif %}
                            </div>
                        {% endif %}
                    </div>
                    <div class="container">
                        <p id="commentOpinion{{comment.pk}}" class="my-0 comment-opinion">{{ comment.opinion }}</p>  
                    </div>
                    <div class="card-body pt-0 comment-info">
                        <span class="option-text">{{ comment.created_at }}</span>
                        <strong class="option-text">좋아요 <strong id="commentLikeCount{{ comment.pk }}">{{ comment.like_users.all|length }}</strong>개</strong>
                    </div>
                {% endfor %}
            </div>
            <hr class="mt-0">
            <div class="card-body pt-0 pb-1">
                {% if request.user in photo.like_users.all %}
                    <i data-photo_pk="{{ photo.pk }}" id="photoLikeButton" class="fas fa-heart photo-liked-heart mr-3"></i>
                {% else %}
                    <i data-photo_pk="{{ photo.pk }}" id="photoLikeButton" class="far fa-heart photo-unliked-heart mr-3"></i>
                {% endif %}
                <i class="far fa-comment mr-3 comment-img"></i>
            </div>
            <div class="mt-2 ml-3">
                <strong>좋아요 <strong id="photoLikeCount{{ photo.pk }}">{{ photo.like_users.all|length }}</strong>개</strong>
            </div>
            <hr class="my-1">
            <form id="commentForm" action="{% url 'photos:create_comment' photo.pk %}" method="POST">
                {% csrf_token %}
                <div class="input-group">
                    <div class="comment-form">
                        {% bootstrap_form form layout='inline' %}
                    </div>
                    <button class="btn btn-default comment-button">게시</button>
                </div>
            </form>
        </div>
        </div>
    </div>
{% endblock %}

photos/templates/photos/photo_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
    <div class="containers">
      <div class="row">
          {% for photo in photos %}
            <div class="col-6 col-md-4 mb-4">
              <a href="{% url 'photos:photo_detail' photo.pk %}">
                <img src="{{ photo.image_thumbnail.url }}" alt="">
              </a>
            </div>
          {% endfor %}
      </div>
    </div>
{% endblock %}