accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.article_list, name='article_list'),
    path('create/', views.create_article, name='create_article'),
    path('<int:article_pk>/', views.article_detail, name='article_detail'),
    path('<int:article_pk>/update/', views.update_article, name='update_article'),
    path('<int:article_pk>/delete/', views.delete_article, name='delete_article'),
    path('<int:article_pk>/comment/create/', views.create_comment, name='create_comment'),
    path('<int:article_pk>/<int:comment_pk>/comment/update/', views.update_comment, name='update_comment'),
    path('<int:article_pk>/<int:comment_pk>/comment/delete/', views.delete_comment, name='delete_comment'),
    path('<int:article_pk>/like/', views.like_article, name='like_article'),
]

hemstagram/urls.py
from django.contrib import admin
from django.urls import path, include
from articles import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('photos/', include('photos.urls')),
    path('', views.article_list),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photos/urls.py
from django.urls import path
from . import views

app_name = 'photos'

urlpatterns = [
    path('', views.photo_list, name='photo_list'),
    path('create/', views.create_photo, name='create_photo'),
    path('<int:photo_pk>/', views.photo_detail, name='photo_detail'),
    path('<int:photo_pk>/update/', views.update_photo, name='update_photo'),
    path('<int:photo_pk>/delete/', views.delete_photo, name='delete_photo'),
    path('<int:photo_pk>/comments/', views.create_comment, name='create_comment'),
    path('<int:photo_pk>/comments/<int:comment_pk>/update/', views.update_comment, name='update_comment'),
    path('<int:photo_pk>/comments/<int:comment_pk>/delete/', views.delete_comment, name='delete_comment'),
    path('<int:photo_pk>/like/', views.like_photo, name='like_photo'),
    path('<int:photo_pk>/comments/<int:comment_pk>/like/', views.like_comment, name='like_comment'),
]

templates/_nav.html
{% load static %}

{% block static %}
<link rel="stylesheet" href="{% static 'css/nav.css' %}">
{% endblock %}

<nav class="navbar navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand title" href="{% url 'articles:article_list' %}">
            <i class="fas fa-heart" style="color:pink;"></i>
            <strong>Hemstagram</strong>
        </a>
        <ul class="nav justify-content-end">
          <li class="nav-item mx-3">
            <a class="nav-menu" href="{% url 'articles:article_list' %}"><i class="fas fa-home"></i></a>
          </li>
          <li class="nav-item mx-3">
            <a class="nav-menu" href="{% url 'articles:create_article' %}"><i class="fas fa-pen"></i></a>
          </li>
          <li class="nav-item mx-3">
            <a class="nav-menu" href="{% url 'photos:photo_list' %}"><i class="fas fa-camera"></i></a>
          </li>
          <li class="nav-item mx-3">
            <a class="nav-menu" href="{% url 'photos:create_photo' %}"><i class="fas fa-upload"></i></a>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item mx-3">
              <a class="nav-menu" href="{% url 'accounts:logout' %}"><i class="fas fa-sign-out-alt"></i></a>
            </li>
          {% else %}
            <li class="nav-item mx-3">
              <a class="nav-menu" href="{% url 'accounts:signup' %}"><i class="fas fa-user-plus"></i></a>
            </li>
          {% endif %}
        </ul>
    </div>
</nav>

templates/base.html
{% load static %}
{% load bootstrap4 %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Hamstagram{% block title %}{% endblock %}</title>
    <link rel="shortcut icon" href="#">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script" rel="stylesheet">
    {% bootstrap_css %}
    {% block static %}
    {% endblock %}
</head>
<body>
    {% include '_nav.html' %}
    {% if messages %}
        {% for message in messages %}
        <div {% if message.tags %} class="alert alert-danger"{% endif %}>{{ message }}</div>
        {% endfor %}
    {% endif %}
    <div class="container mt-5 px-0">
        {% block body %}
        {% endblock %}
    </div>
    <script src="https://kit.fontawesome.com/01901fb831.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/01901fb831.js" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    {% bootstrap_javascript jquery='full' %}
</body>
</html>